name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run tests with coverage
        run: |
          npx mocha --require mocha-steps --exit \
            --reporter mocha-junit-reporter \
            --reporter-options mochaFile=./coverage/test-results.xml \
            --reporter mocha-junit-reporter \
            --reporter-options mochaFile=./coverage/lcov-report/cobertura.xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov-report/cobertura.xml
